### ISSUE TITLE
Requires package for installation using pipenv tool

### ISSUE THREAD

**Issue by snurbol** [xente/loguru-loki-handlers#4]
Requires packaging your project in a Python package for installation. So that we can easily and legally use your work. Thanks for the work you've done!

In the case of pip install, it is possible to install from the github repository, but pipenv refuses to install. It's not difficult at all. In addition, githib already has a Workflow template for building and publishing a package in pipy. You just need to register on pipy and enter the received token into CI Workflow

**Comment by snurbol** [comment]
Sorry! My mistake!

**Comment by snurbol** [comment]
Can you write in README file your pipy package name? When I try to install a package I get an error:
`ERROR: No matching distribution found for loguru-loki-handlers`

**Comment by xente** [comment]
Hi, 

Sorry i have to update the documentation. I will try to fix the issue related with the pipenv

Let me know if all is working fine for you.
