### ISSUE TITLE
How should I use the "labelkeys" parameter of loki_handler class?

### ISSUE THREAD

**Issue by wnark** [xente/loguru-loki-handlers#7]
How should I use the "labelkeys" parameter of loki_handler class? The document is not written

![image](https://github.com/xente/loguru-loki-handlers/assets/24355466/d387be8d-1d03-49a0-b0fa-234b1f5730ec)

**Comment by wnark** [comment]
I checked the source code to see that both labels and labelkeys can add labels, what is the difference between them?

**Comment by wnark** [comment]
If you look at the code according to this

```
        for key, val in simplified.items():
            if key in self.labelKeys:
                self.steam.addLabel(key, val)
```
It's more appropriate to use a list for labelkeys, right? Is the use of dictionaries on your side a convenient way to use values as comments?

**Comment by wnark** [comment]
I know why labelKeys cannot take effect. It is recommended to use:
```
        for key, val in simplified.items():
            if key in self.labelKeys:
                self.steam.addLabel(key, str(val))
```
Because val is not necessarily a string by default

**Comment by xente** [comment]
You can add it on init like this
`logger.configure(handlers=[{"sink": LokiHandler(os.environ["LOKI_URL"],
                                                        {"Application": os.environ["APPLICATION"],
                                                         "Environment": os.environ["STAGE"]}), "serialize": True}])`

For me it is working, Did you configured in this way your logger handler?

**Comment by wnark** [comment]
It's a bit similar. I was just curious about why the variable labelkeys was not used in the readme. Then I read it several times and discovered its use.
When labelkeys is a dictionary {"timestap":"123123"},like：
logger.configure(handlers=[{"sink": LokiHandler(os.environ["LOKI_URL"], {"Application": os.environ["APPLICATION"], "Environment": os.environ["STAGE"]},{"timestap":"123123"}), "serialize": True}])

 the val in self.steam.addLabel(key, val) is of type int, which will result in no timestap label, so it is recommended to use str(val)

**Comment by wnark** [comment]
#8
